#!/usr/bin/env bash
: "${ROOKI_DEBUG:=}"
: "${XDG_CONFIG_HOME:=$HOME/.config}"
[[ -n "$ROOKI_DEBUG" ]] && set -ux
readonly config_folder="$XDG_CONFIG_HOME/rooki"
readonly src=$(readlink -f "$1")
readonly bin=$config_folder/$(md5sum "$src" | awk '{print $1}')
if [[ -x "$bin" ]]; then
  shift 1; "$bin" "$@";
else
  mkdir -p "$config_folder"
  f=$(mktemp)
  sed "/^#!.*/d" "$src" > "$f" # remove shbang from src file to compile
  for fl in $(sed -n "s/.*rooki:\(\S\+\).*/\1/gp" "$src" | sort -u); do
    eval "$fl=\"$(awk -F "rooki:$fl *" "{print \$2}" "$src" | paste -s)\""
  done
  eval "$spell" && # cast the spell
  { [[ -n "$ROOKI_DEBUG" ]] || rm "$f"; } && # remove temporary file if no debug
  [[ -x "$bin" ]] && "$0" "$@" # if the binary was created, run rooki again
fi
